# Generated by Django 5.2.5 on 2026-02-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('literature', 'Литература'), ('prose', 'Проза'), ('comics', 'Комиксы'), ('fairy_tales', 'Сказки')], max_length=50, null=True),
        ),
    ]
