# Generated by Django 5.2.11 on 2026-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_slug_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.JSONField(default=list),
        ),
    ]
