# Generated by Django 5.2.11 on 2026-02-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_ratings_book_ratings_json_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ratings_json',
            new_name='ratings',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
