# Generated by Django 5.2.11 on 2026-03-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_book_ratings_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
