# Generated by Django 5.2.11 on 2026-04-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
    ]
