# Generated by Django 5.2.11 on 2026-04-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_notification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='history',
        ),
    ]
