# Generated by Django 5.2.11 on 2026-04-24 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_paymentrequest_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='history',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
